FROM mysql:5.7

LABEL maintainer="Bo-Yi Wu <appleboy.tw@gmail.com>" \
  org.label-schema.name="docker-backup-database" \
  org.label-schema.vendor="Bo-Yi Wu" \
  org.label-schema.schema-version="1.0"

EXPOSE 3306

COPY release/linux/amd64/backup /bin/

ENTRYPOINT ["/bin/backup"]
